apiVersion: v1
kind: Service
metadata:
  labels:
    app: slave-nodes
  name: slave-nodes
spec:
  type: LoadBalancer
  ports:
    - name: nodemanager
      port: 22004
      targetPort: 22004
      protocol: TCP
      
    - name: websocket
      port: 22005
      targetPort: 22005
      protocol: TCP

  selector:
    app: slave-nodes
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: slave-nodes
  labels:
    app: slave-nodes
spec:
  selector:
    matchLabels:
      app: slave-nodes
  template:
    metadata:
      labels:
        app: slave-nodes
    spec:
      nodeSelector:
          master: "false"
        
      containers:
        - image: <hosted image url>
          name: slave-node
          env:
          - name: podName
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
                
          ports:
          - containerPort: 22000
            name: rpc
          - containerPort: 22001
            name: whisper
          - containerPort: 22002
            name: constellation
          - containerPort: 22003
            name: raft
          - containerPort: 22004
            name: nodemanager
          - containerPort: 22005
            name: websocket
            
          args:
          - /bin/sh
          - -c
          - "cp -r tmp/lib home/lib && cp tmp/setup.sh home/ && cp tmp/qm.variables home/ && cd home && ./setup.sh join -n $podName --oip 35.194.26.59 --onm 22004 --tip $POD_IP -r 22000 -w 22001 -c 22002 --raft 22003 --nm 22004 --ws 22005 -d"
          




